import type { Metadata } from "next";
import { ReactNode } from "react";

import { ClerkProvider } from "@clerk/nextjs";

import { ThreadModalProvider } from "@/hooks/useThreadModal";

import NewThreadModal from "@/components/modals/newThreadModal/newThreadModal";
import Menu from "@/components/navigation/menu/Menu";
import SideBar from "@/components/navigation/sidebar/SideBar";

import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThreadModalProvider>
        <html lang="en">
          <body>
            <NewThreadModal />
            <Toaster />
            <div className="app-sections">
              <Menu />
              <div className="content">{children}</div>
              <SideBar />
            </div>
          </body>
        </html>
      </ThreadModalProvider>
    </ClerkProvider>
  );
}
