import type { Metadata } from "next";
import { ReactNode } from "react";

import { ClerkProvider } from "@clerk/nextjs";

import Menu from "@/components/navigation/menu/Menu";
import SideBar from "@/components/navigation/sidebar/SideBar";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className="app-sections">
            <Menu />
            <div className="content">{children}</div>
            <SideBar />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
